### ISSUE TITLE
Random connection issues when attempting to add a contact

### ISSUE THREAD

**Issue by alehar9320** [frapperino/sketchagram#33]
05-01 17:22:40.723    6525-6542/sketchagram.chalmers.com.sketchagram W/Binder﹕ Caught a RuntimeException from the binder stub implementation.
    java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.android.internal.textservice.ISpellCheckerSession.asBinder()' on a null object reference
            at android.view.textservice.SpellCheckerSession$SpellCheckerSessionListenerImpl.onServiceConnected(SpellCheckerSession.java:330)
            at android.view.textservice.SpellCheckerSession$InternalListener.onServiceConnected(SpellCheckerSession.java:473)
            at com.android.internal.textservice.ITextServicesSessionListener$Stub.onTransact(ITextServicesSessionListener.java:54)
            at android.os.Binder.execTransact(Binder.java:446)
05-01 17:22:43.679    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ org.jivesoftware.smack.SmackException$NotConnectedException
05-01 17:22:43.680    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at org.jivesoftware.smack.XMPPConnection.sendPacket(XMPPConnection.java:584)
05-01 17:22:43.680    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at org.jivesoftware.smack.XMPPConnection.createPacketCollectorAndSend(XMPPConnection.java:793)
05-01 17:22:43.680    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at org.jivesoftware.smackx.search.UserSearch.getSearchForm(UserSearch.java:72)
05-01 17:22:43.680    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at org.jivesoftware.smackx.search.UserSearchManager.getSearchForm(UserSearchManager.java:76)
05-01 17:22:43.680    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at sketchagram.chalmers.com.network.Connection.searchUsers(Connection.java:439)
05-01 17:22:43.680    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at sketchagram.chalmers.com.network.Connection.addContact(Connection.java:361)
05-01 17:22:43.680    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at sketchagram.chalmers.com.model.User.addContact(User.java:78)
05-01 17:22:43.680    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at sketchagram.chalmers.com.sketchagram.MainActivity$6.onClick(MainActivity.java:298)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at android.view.View.performClick(View.java:4780)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at android.view.View$PerformClick.run(View.java:19866)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:739)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5254)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-01 17:22:43.683    6525-6525/sketchagram.chalmers.com.sketchagram W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
05-01 17:22:43.788    6525-6525/sketchagram.chalmers.com.sketchagram W/IInputConnectionWrapper﹕ finishComposingText on inactive InputConnection

**Comment by ollmatt** [comment]
This is due to not being connected to the server maybe we should indicate this somehow
